// Generated by tools/build-special-liturgies.py; edit tools/special_liturgies/*.py.
globalThis.countrySpecialLiturgies = {
  "schemaVersion": 1,
  "universal": {
    "allSouls": {
      "first": {
        "names": {
          "KR": "위령의날 첫째미사",
          "VN": "Lễ cầu cho các tín hữu đã qua đời – Lễ I",
          "EN": "All Souls' Day – First Mass",
          "JP": "死者の日 第一ミサ",
          "LA": "In Commemoratione Omnium Fidelium Defunctorum – Missa I",
          "ZH": "追思已亡諸靈日 第一台彌撒",
          "IT": "Commemorazione dei fedeli defunti – Prima Messa",
          "PT": "Comemoração dos fiéis defuntos – Primeira Missa",
          "ES": "Conmemoración de los fieles difuntos – Primera Misa",
          "DE": "Allerseelen – Erste Messe"
        },
        "data": {}
      },
      "second": {
        "names": {
          "KR": "위령의날 둘째미사",
          "VN": "Lễ cầu cho các tín hữu đã qua đời – Lễ II",
          "EN": "All Souls' Day – Second Mass",
          "JP": "死者の日 第二ミサ",
          "LA": "In Commemoratione Omnium Fidelium Defunctorum – Missa II",
          "ZH": "追思已亡諸靈日 第二台彌撒",
          "IT": "Commemorazione dei fedeli defunti – Seconda Messa",
          "PT": "Comemoração dos fiéis defuntos – Segunda Missa",
          "ES": "Conmemoración de los fieles difuntos – Segunda Misa",
          "DE": "Allerseelen – Zweite Messe"
        },
        "data": {}
      },
      "third": {
        "names": {
          "KR": "위령의날 셋째미사",
          "VN": "Lễ cầu cho các tín hữu đã qua đời – Lễ III",
          "EN": "All Souls' Day – Third Mass",
          "JP": "死者の日 第三ミサ",
          "LA": "In Commemoratione Omnium Fidelium Defunctorum – Missa III",
          "ZH": "追思已亡諸靈日 第三台彌撒",
          "IT": "Commemorazione dei fedeli defunti – Terza Messa",
          "PT": "Comemoração dos fiéis defuntos – Terceira Missa",
          "ES": "Conmemoración de los fieles difuntos – Tercera Misa",
          "DE": "Allerseelen – Dritte Messe"
        },
        "data": {}
      }
    },
    "vigils": [
      {
        "id": "christmas_vigil",
        "monthDay": "12-24",
        "hour": 19,
        "color": "gold",
        "names": {
          "KR": "주님 성탄 대축일 전야미사",
          "VN": "Lễ Vọng Giáng Sinh",
          "EN": "The Nativity of the Lord – Vigil Mass",
          "JP": "主の降誕 前晩のミサ",
          "LA": "In Vigilia Nativitatis Domini",
          "ZH": "耶穌聖誕節 前夕彌撒",
          "IT": "Natale del Signore – Messa vespertina nella vigilia",
          "PT": "Natal do Senhor – Missa da vigília",
          "ES": "Natividad del Señor – Misa de la vigilia",
          "DE": "Weihnachten – Messe am Heiligen Abend"
        },
        "data": {}
      },
      {
        "id": "easter_vigil",
        "easterOffset": -1,
        "hour": 19,
        "color": "gold",
        "names": {
          "KR": "주님 부활 대축일 파스카 성야",
          "VN": "Đêm Canh Thức Vượt Qua",
          "EN": "Easter Vigil in the Holy Night",
          "JP": "復活の聖なる徹夜祭",
          "LA": "Vigilia Paschalis in Nocte Sancta",
          "ZH": "復活節前夕守夜禮",
          "IT": "Veglia pasquale nella notte santa",
          "PT": "Vigília Pascal na Noite Santa",
          "ES": "Vigilia Pascual en la Noche Santa",
          "DE": "Die Feier der Osternacht"
        },
        "data": {}
      }
    ]
  },
  "countries": {
    "AU": {
      "jurisdiction": "AU",
      "vigils": [],
      "allSouls": {}
    },
    "BR": {
      "jurisdiction": "BR",
      "vigils": [],
      "allSouls": {}
    },
    "GB-ENG": {
      "jurisdiction": [
        "GB-ENG",
        "GB-WLS"
      ],
      "vigils": [],
      "allSouls": {}
    },
    "GB-WLS": {
      "jurisdiction": [
        "GB-ENG",
        "GB-WLS"
      ],
      "vigils": [],
      "allSouls": {}
    },
    "DE": {
      "jurisdiction": "DE",
      "vigils": [],
      "allSouls": {}
    },
    "INTL": {
      "jurisdiction": "INTL",
      "vigils": [],
      "allSouls": {}
    },
    "IE": {
      "jurisdiction": "IE",
      "vigils": [],
      "allSouls": {}
    },
    "IT": {
      "jurisdiction": "IT",
      "vigils": [],
      "allSouls": {}
    },
    "JP": {
      "jurisdiction": "JP",
      "vigils": [],
      "allSouls": {}
    },
    "KR": {
      "jurisdiction": "KR",
      "vigils": [],
      "allSouls": {}
    },
    "MX": {
      "jurisdiction": "MX",
      "vigils": [],
      "allSouls": {}
    },
    "NZ": {
      "jurisdiction": "NZ",
      "vigils": [],
      "allSouls": {}
    },
    "PH": {
      "jurisdiction": "PH",
      "vigils": [],
      "allSouls": {}
    },
    "PT": {
      "jurisdiction": "PT",
      "vigils": [],
      "allSouls": {}
    },
    "GB-SCT": {
      "jurisdiction": "GB-SCT",
      "vigils": [],
      "allSouls": {}
    },
    "TW": {
      "jurisdiction": "TW",
      "vigils": [],
      "allSouls": {}
    },
    "US": {
      "jurisdiction": "US",
      "vigils": [],
      "allSouls": {}
    },
    "VA": {
      "jurisdiction": "VA",
      "vigils": [],
      "allSouls": {}
    },
    "VN": {
      "jurisdiction": "VN",
      "vigils": [
        {
          "id": "saint_joseph_vigil",
          "dates": [],
          "hour": 19,
          "color": "white",
          "names": {
            "KR": "복되신 동정 마리아의 배필 성 요셉 대축일 전야미사",
            "VN": "Lễ vọng Thánh Giuse, bạn trăm năm Đức Maria",
            "EN": "Saint Joseph, Spouse of the Blessed Virgin Mary – Vigil Mass"
          },
          "data": {},
          "sourceUrls": {}
        }
      ],
      "allSouls": {}
    }
  }
};
