// V27.7: query this table only for KR. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "ko",
  "appLanguage": "KR",
  "label": "한국어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "Existing app bibleMap; Korean full names from notation audit",
  "books": {
    "GEN": {"koreanName":"창세기","name":"창세기","aliases":["창세","창세기"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"탈출기","aliases":["탈출","탈출기"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"레위기","aliases":["레위","레위기"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"민수기","aliases":["민수","민수기"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"신명기","aliases":["신명","신명기"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"여호수아기","aliases":["여호","여호수아기"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"판관기","aliases":["판관","판관기"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"룻기","aliases":["룻","룻기"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"사무엘기 상권","aliases":["1사무","사무엘기 상권"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"사무엘기 하권","aliases":["2사무","사무엘기 하권"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"열왕기 상권","aliases":["1열왕","열왕기 상권"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"열왕기 하권","aliases":["2열왕","열왕기 하권"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"역대기 상권","aliases":["1역대","역대기 상권"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"역대기 하권","aliases":["2역대","역대기 하권"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"에즈라기","aliases":["에즈","에즈라기"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"느헤미야기","aliases":["느헤","느헤미야기"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"토빗기","aliases":["토빗","토빗기"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"유딧기","aliases":["유딧","유딧기"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"에스테르기","aliases":["에스","에스테르기"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"마카베오기 상권","aliases":["1마카","마카베오기 상권"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"마카베오기 하권","aliases":["2마카","마카베오기 하권"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"욥기","aliases":["욥","욥기"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"시편","aliases":["시편"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"잠언","aliases":["잠언"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"코헬렛","aliases":["코헬","코헬렛"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"아가","aliases":["아가"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"지혜서","aliases":["지혜","지혜서"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"집회서","aliases":["집회","집회서"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"이사야서","aliases":["이사","이사야서"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"예레미야서","aliases":["예레","예레미야서"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"애가","aliases":["애가"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"바룩서","aliases":["바룩","바룩서"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"에제키엘서","aliases":["에제","에제키엘서"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"다니엘서","aliases":["다니","다니엘서"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"호세아서","aliases":["호세","호세아서"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"요엘서","aliases":["요엘","요엘서"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"아모스서","aliases":["아모","아모스서"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"오바드야서","aliases":["오바","오바드야서"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"요나서","aliases":["요나","요나서"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"미카서","aliases":["미카","미카서"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"나훔서","aliases":["나훔","나훔서"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"하바쿡서","aliases":["하바","하바쿡서"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"스바니야서","aliases":["스파","스바니야서"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"하까이서","aliases":["학개","하까이서"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"즈카르야서","aliases":["즈카","즈카르야서"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"말라키서","aliases":["말라","말라키서"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"마태오 복음","aliases":["마태","마태오 복음","마태오"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"마르코 복음","aliases":["마르","마르코 복음","마르코"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"루카 복음","aliases":["루카","루카 복음"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"요한 복음","aliases":["요한","요한 복음"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"사도행전","aliases":["사도","사도행전"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"로마서","aliases":["로마","로마서"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"코린토 1서","aliases":["1코린","코린토 1서"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"코린토 2서","aliases":["2코린","코린토 2서"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"갈라티아서","aliases":["갈라","갈라티아서"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"에페소서","aliases":["에페","에페소서"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"필리피서","aliases":["필리","필리피서"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"콜로새서","aliases":["콜로","콜로새서"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"테살로니카 1서","aliases":["1테살","테살로니카 1서"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"테살로니카 2서","aliases":["2테살","테살로니카 2서"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"티모테오 1서","aliases":["1티모","티모테오 1서"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"티모테오 2서","aliases":["2티모","티모테오 2서"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"티토서","aliases":["티토","티토서"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"필레몬서","aliases":["필레","필레몬서"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"히브리서","aliases":["히브","히브리서"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"야고보서","aliases":["야고","야고보서"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"베드로 1서","aliases":["1베드","베드로 1서"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"베드로 2서","aliases":["2베드","베드로 2서"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"요한 1서","aliases":["1요한","요한 1서"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"요한 2서","aliases":["2요한","요한 2서"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"요한 3서","aliases":["3요한","요한 3서"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"유다서","aliases":["유다","유다서"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"요한 묵시록","aliases":["묵시","요한 묵시록"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
