// V27.7: query this table only for EN. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "en",
  "appLanguage": "EN",
  "label": "영어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "Existing app bibleMap abbreviations plus English full book names",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Genesis","aliases":["Gn","Genesis"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Exodus","aliases":["Ex","Exodus"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Leviticus","aliases":["Lv","Leviticus"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Numbers","aliases":["Nm","Numbers"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Deuteronomy","aliases":["Dt","Deuteronomy"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Joshua","aliases":["Jos","Joshua"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Judges","aliases":["Jgs","Judges"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Ruth","aliases":["Ru","Ruth"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Samuel","aliases":["1 Sm","1 Samuel"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Samuel","aliases":["2 Sm","2 Samuel"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Kings","aliases":["1 Kgs","1 Kings"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Kings","aliases":["2 Kgs","2 Kings"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Chronicles","aliases":["1 Chr","1 Chronicles"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Chronicles","aliases":["2 Chr","2 Chronicles"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Ezra","aliases":["Ezr","Ezra"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Nehemiah","aliases":["Neh","Nehemiah"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tobit","aliases":["Tb","Tobit"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Judith","aliases":["Jdt","Judith"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Esther","aliases":["Est","Esther"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Maccabees","aliases":["1 Mc","1 Maccabees"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Maccabees","aliases":["2 Mc","2 Maccabees"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Job","aliases":["Jb","Job"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Psalms","aliases":["Ps","Psalms"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Proverbs","aliases":["Prv","Proverbs"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Ecclesiastes","aliases":["Eccl","Ecclesiastes"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Song of Songs","aliases":["Song","Song of Songs"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Wisdom","aliases":["Wis","Wisdom"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Sirach","aliases":["Sir","Sirach"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Isaiah","aliases":["Is","Isaiah"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Jeremiah","aliases":["Jer","Jeremiah"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Lamentations","aliases":["Lam","Lamentations"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Baruch","aliases":["Bar","Baruch"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ezekiel","aliases":["Ez","Ezekiel"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Daniel","aliases":["Dn","Daniel"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Hosea","aliases":["Hos","Hosea"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Joel","aliases":["Jl","Joel"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Amos","aliases":["Am","Amos"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Obadiah","aliases":["Ob","Obadiah"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Jonah","aliases":["Jon","Jonah"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Micah","aliases":["Mi","Micah"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Nahum","aliases":["Na","Nahum"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Habakkuk","aliases":["Hb","Habakkuk"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Zephaniah","aliases":["Zep","Zephaniah"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Haggai","aliases":["Hg","Haggai"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Zechariah","aliases":["Zec","Zechariah"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Malachi","aliases":["Mal","Malachi"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Matthew","aliases":["Mt","Matthew"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Mark","aliases":["Mk","Mark"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Luke","aliases":["Lk","Luke"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"John","aliases":["Jn","John"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Acts","aliases":["Acts"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Romans","aliases":["Rom","Romans"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Corinthians","aliases":["1 Cor","1 Corinthians"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Corinthians","aliases":["2 Cor","2 Corinthians"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Galatians","aliases":["Gal","Galatians"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Ephesians","aliases":["Eph","Ephesians"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Philippians","aliases":["Phil","Philippians"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Colossians","aliases":["Col","Colossians"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Thessalonians","aliases":["1 Thes","1 Thessalonians"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Thessalonians","aliases":["2 Thes","2 Thessalonians"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Timothy","aliases":["1 Tm","1 Timothy"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Timothy","aliases":["2 Tm","2 Timothy"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Titus","aliases":["Ti","Titus"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Philemon","aliases":["Phlm","Philemon"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hebrews","aliases":["Heb","Hebrews"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"James","aliases":["Jas","James"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Peter","aliases":["1 Pt","1 Peter"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Peter","aliases":["2 Pt","2 Peter"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 John","aliases":["1 Jn","1 John"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 John","aliases":["2 Jn","2 John"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 John","aliases":["3 Jn","3 John"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Jude","aliases":["Jude"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Revelation","aliases":["Rv","Revelation"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
