// V27.7: query this table only for PT. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "pt",
  "appLanguage": "PT",
  "label": "포르투갈어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "BIBLE_NOTATION_AUDIT_V27_7.md section 2",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Génesis / Gênesis","aliases":["Gn","Génesis / Gênesis"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Êxodo","aliases":["Ex","Êxodo"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Levítico","aliases":["Lv","Levítico"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Números","aliases":["Nm","Números"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Deuteronómio / Deuteronômio","aliases":["Dt","Deuteronómio / Deuteronômio"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Josué","aliases":["Js","Josué"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Juízes","aliases":["Jz","Juízes"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Rute","aliases":["Rt","Rute"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Samuel","aliases":["1Sm","1 Samuel"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Samuel","aliases":["2Sm","2 Samuel"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Reis","aliases":["1Rs","1 Reis"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Reis","aliases":["2Rs","2 Reis"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Crónicas / Crônicas","aliases":["1Cr","1 Crónicas / Crônicas"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Crónicas / Crônicas","aliases":["2Cr","2 Crónicas / Crônicas"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Esdras","aliases":["Esd","Esdras"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Neemias","aliases":["Ne","Neemias"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tobias","aliases":["Tb","Tobias"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Judite","aliases":["Jdt","Judite"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Ester","aliases":["Est","Ester"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Macabeus","aliases":["1Mac","1Mc","1 Macabeus"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Macabeus","aliases":["2Mac","2Mc","2 Macabeus"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Job / Jó","aliases":["Job","Jó","Job / Jó"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Salmos","aliases":["Sl","Sal","Salmos"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Provérbios","aliases":["Pr","Prv","Provérbios"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Eclesiastes / Coélet","aliases":["Ecl","Qo","Eclesiastes / Coélet"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Cântico dos Cânticos","aliases":["Ct","Cântico dos Cânticos"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Sabedoria","aliases":["Sb","Sab","Sabedoria"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Ben Sira / Eclesiástico","aliases":["Sir","Eclo","Ben Sira / Eclesiástico"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Isaías","aliases":["Is","Isaías"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Jeremias","aliases":["Jr","Jeremias"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Lamentações","aliases":["Lm","Lamentações"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Baruc","aliases":["Br","Bar","Baruc"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ezequiel","aliases":["Ez","Ezequiel"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Daniel","aliases":["Dn","Daniel"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Oseias / Oséias","aliases":["Os","Oseias / Oséias"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Joel","aliases":["Jl","Joel"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Amós","aliases":["Am","Amós"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Abdias","aliases":["Abd","Ab","Abdias"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Jonas","aliases":["Jn","Jonas"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Miqueias","aliases":["Mq","Miqueias"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Naum","aliases":["Na","Naum"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Habacuc","aliases":["Hab","Habacuc"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Sofonias","aliases":["Sf","Sofonias"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Ageu","aliases":["Ag","Ageu"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Zacarias","aliases":["Zc","Zacarias"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Malaquias","aliases":["Ml","Malaquias"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Mateus","aliases":["Mt","Mateus"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Marcos","aliases":["Mc","Marcos"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Lucas","aliases":["Lc","Lucas"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"João","aliases":["Jo","João"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Atos / Actos dos Apóstolos","aliases":["At","Act","Atos / Actos dos Apóstolos"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Romanos","aliases":["Rm","Romanos"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Coríntios","aliases":["1Cor","1 Coríntios"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Coríntios","aliases":["2Cor","2 Coríntios"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Gálatas","aliases":["Gl","Gal","Gálatas"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Efésios","aliases":["Ef","Efésios"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Filipenses","aliases":["Fl","Flp","Filipenses"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Colossenses","aliases":["Cl","Col","Colossenses"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Tessalonicenses","aliases":["1Ts","1Tess","1 Tessalonicenses"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Tessalonicenses","aliases":["2Ts","2Tess","2 Tessalonicenses"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Timóteo","aliases":["1Tm","1Tim","1 Timóteo"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Timóteo","aliases":["2Tm","2Tim","2 Timóteo"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Tito","aliases":["Tt","Tito"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Filémon / Filêmon","aliases":["Flm","Fm","Filémon / Filêmon"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hebreus","aliases":["Hb","Heb","Hebreus"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Tiago","aliases":["Tg","Tiago"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Pedro","aliases":["1Pd","1Pe","1 Pedro"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Pedro","aliases":["2Pd","2Pe","2 Pedro"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 João","aliases":["1Jo","1 João"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 João","aliases":["2Jo","2 João"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 João","aliases":["3Jo","3 João"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Judas","aliases":["Jd","Judas"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Apocalipse","aliases":["Ap","Apocalipse"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
