// V27.7: query this table only for IT. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "it",
  "appLanguage": "IT",
  "label": "이탈리아어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "BIBLE_NOTATION_AUDIT_V27_7.md section 2",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Genesi","aliases":["Gen","Gn","Genesi"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Esodo","aliases":["Es","Esodo"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Levitico","aliases":["Lv","Levitico"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Numeri","aliases":["Nm","Numeri"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Deuteronomio","aliases":["Dt","Deuteronomio"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Giosuè","aliases":["Gs","Giosuè"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Giudici","aliases":["Gdc","Giudici"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Rut","aliases":["Rt","Rut"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Samuele","aliases":["1Sam","1 Samuele"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Samuele","aliases":["2Sam","2 Samuele"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Re","aliases":["1Re","1 Re"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Re","aliases":["2Re","2 Re"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Cronache","aliases":["1Cr","1 Cronache"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Cronache","aliases":["2Cr","2 Cronache"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Esdra","aliases":["Esd","Esdra"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Neemia","aliases":["Ne","Neemia"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tobia / Tobi","aliases":["Tb","Tobia / Tobi"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Giuditta","aliases":["Gdt","Giuditta"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Ester","aliases":["Est","Ester"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Maccabei","aliases":["1Mac","1 Maccabei"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Maccabei","aliases":["2Mac","2 Maccabei"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Giobbe","aliases":["Gb","Giobbe"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Salmi","aliases":["Sal","Salmi"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Proverbi","aliases":["Pr","Prv","Proverbi"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Qoèlet","aliases":["Qo","Qoèlet"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Cantico dei Cantici","aliases":["Ct","Cantico dei Cantici"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Sapienza","aliases":["Sap","Sapienza"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Siracide","aliases":["Sir","Siracide"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Isaia","aliases":["Is","Isaia"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Geremia","aliases":["Ger","Geremia"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Lamentazioni","aliases":["Lam","Lamentazioni"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Baruc","aliases":["Bar","Baruc"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ezechiele","aliases":["Ez","Ezechiele"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Daniele","aliases":["Dn","Daniele"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Osea","aliases":["Os","Osea"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Gioele","aliases":["Gl","Gioele"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Amos","aliases":["Am","Amos"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Abdia","aliases":["Abd","Abdia"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Giona","aliases":["Gio","Gn","Giona"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Michea","aliases":["Mi","Mic","Michea"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Naum","aliases":["Na","Naum"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Abacuc","aliases":["Ab","Abacuc"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Sofonia","aliases":["Sof","Sofonia"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Aggeo","aliases":["Ag","Aggeo"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Zaccaria","aliases":["Zc","Zaccaria"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Malachia","aliases":["Ml","Malachia"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Matteo","aliases":["Mt","Matteo"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Marco","aliases":["Mc","Marco"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Luca","aliases":["Lc","Luca"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"Giovanni","aliases":["Gv","Giovanni"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Atti degli Apostoli","aliases":["At","Atti degli Apostoli"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Romani","aliases":["Rm","Romani"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Corinzi","aliases":["1Cor","1 Corinzi"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Corinzi","aliases":["2Cor","2 Corinzi"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Galati","aliases":["Gal","Galati"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Efesini","aliases":["Ef","Efesini"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Filippesi","aliases":["Fil","Filippesi"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Colossesi","aliases":["Col","Colossesi"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Tessalonicesi","aliases":["1Ts","1 Tessalonicesi"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Tessalonicesi","aliases":["2Ts","2 Tessalonicesi"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Timoteo","aliases":["1Tm","1 Timoteo"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Timoteo","aliases":["2Tm","2 Timoteo"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Tito","aliases":["Tt","Tito"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Filemone","aliases":["Fm","Filemone"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Ebrei","aliases":["Eb","Ebrei"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Giacomo","aliases":["Gc","Giacomo"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Pietro","aliases":["1Pt","1 Pietro"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Pietro","aliases":["2Pt","2 Pietro"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 Giovanni","aliases":["1Gv","1 Giovanni"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 Giovanni","aliases":["2Gv","2 Giovanni"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 Giovanni","aliases":["3Gv","3 Giovanni"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Giuda","aliases":["Gd","Giuda"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Apocalisse","aliases":["Ap","Apocalisse"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
