// V27.7: query this table only for ES. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "es",
  "appLanguage": "ES",
  "label": "스페인어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "BIBLE_NOTATION_AUDIT_V27_7.md section 2",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Génesis","aliases":["Gn","Gén","Génesis"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Éxodo","aliases":["Ex","Éx","Éxodo"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Levítico","aliases":["Lv","Levítico"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Números","aliases":["Nm","Núm","Números"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Deuteronomio","aliases":["Dt","Deuteronomio"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Josué","aliases":["Jos","Josué"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Jueces","aliases":["Jc","Jueces"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Rut","aliases":["Rt","Rut"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Samuel","aliases":["1Sam","1 Samuel"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Samuel","aliases":["2Sam","2 Samuel"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Reyes","aliases":["1Re","1 Reyes"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Reyes","aliases":["2Re","2 Reyes"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Crónicas","aliases":["1Cr","1 Crónicas"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Crónicas","aliases":["2Cr","2 Crónicas"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Esdras","aliases":["Esd","Esdras"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Nehemías","aliases":["Neh","Nehemías"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tobías","aliases":["Tb","Tobías"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Judit","aliases":["Jdt","Judit"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Ester","aliases":["Est","Ester"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Macabeos","aliases":["1Mac","1 Macabeos"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Macabeos","aliases":["2Mac","2 Macabeos"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Job","aliases":["Job"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Salmos","aliases":["Sal","Salmos"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Proverbios","aliases":["Pr","Prov","Proverbios"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Eclesiastés / Qohélet","aliases":["Qo","Ecl","Eclesiastés / Qohélet"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Cantar de los Cantares","aliases":["Ct","Cant","Cantar de los Cantares"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Sabiduría","aliases":["Sb","Sab","Sabiduría"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Eclesiástico / Sirácida","aliases":["Si","Eclo","Eclesiástico / Sirácida"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Isaías","aliases":["Is","Isaías"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Jeremías","aliases":["Jr","Jer","Jeremías"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Lamentaciones","aliases":["Lm","Lamentaciones"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Baruc","aliases":["Ba","Bar","Baruc"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ezequiel","aliases":["Ez","Ezequiel"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Daniel","aliases":["Dn","Daniel"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Oseas","aliases":["Os","Oseas"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Joel","aliases":["Jl","Joel"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Amós","aliases":["Am","Amós"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Abdías","aliases":["Abd","Ab","Abdías"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Jonás","aliases":["Jon","Jonás"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Miqueas","aliases":["Mi","Miq","Miqueas"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Nahúm","aliases":["Na","Nah","Nahúm"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Habacuc","aliases":["Ha","Hab","Habacuc"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Sofonías","aliases":["So","Sof","Sofonías"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Ageo","aliases":["Ag","Ageo"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Zacarías","aliases":["Za","Zac","Zacarías"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Malaquías","aliases":["Ml","Mal","Malaquías"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Mateo","aliases":["Mt","Mateo"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Marcos","aliases":["Mc","Marcos"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Lucas","aliases":["Lc","Lucas"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"Juan","aliases":["Jn","Juan"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Hechos de los Apóstoles","aliases":["Hch","Hechos de los Apóstoles"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Romanos","aliases":["Rm","Rom","Romanos"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Corintios","aliases":["1Co","1Cor","1 Corintios"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Corintios","aliases":["2Co","2Cor","2 Corintios"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Gálatas","aliases":["Ga","Gál","Gálatas"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Efesios","aliases":["Ef","Efesios"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Filipenses","aliases":["Flp","Filipenses"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Colosenses","aliases":["Col","Colosenses"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Tesalonicenses","aliases":["1Ts","1Tes","1 Tesalonicenses"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Tesalonicenses","aliases":["2Ts","2Tes","2 Tesalonicenses"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Timoteo","aliases":["1Tm","1Tim","1 Timoteo"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Timoteo","aliases":["2Tm","2Tim","2 Timoteo"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Tito","aliases":["Tt","Tit","Tito"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Filemón","aliases":["Flm","Filemón"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hebreos","aliases":["Hb","Heb","Hebreos"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Santiago","aliases":["St","Sant","Santiago"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Pedro","aliases":["1P","1Pe","1 Pedro"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Pedro","aliases":["2P","2Pe","2 Pedro"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 Juan","aliases":["1Jn","1 Juan"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 Juan","aliases":["2Jn","2 Juan"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 Juan","aliases":["3Jn","3 Juan"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Judas","aliases":["Judas","Jds"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Apocalipsis","aliases":["Ap","Apocalipsis"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
