// V27.7: query this table only for DE. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "gm",
  "appLanguage": "DE",
  "label": "독일어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "BIBLE_NOTATION_AUDIT_V27_7.md section 2",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Genesis","aliases":["Gen","Genesis"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Exodus","aliases":["Ex","Exodus"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Levitikus","aliases":["Lev","Levitikus"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Numeri","aliases":["Num","Numeri"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Deuteronomium","aliases":["Dtn","Deuteronomium"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Josua","aliases":["Jos","Josua"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Richter","aliases":["Ri","Richter"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Rut","aliases":["Rut"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Samuel","aliases":["1 Sam","1 Samuel"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Samuel","aliases":["2 Sam","2 Samuel"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Könige","aliases":["1 Kön","1 Könige"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Könige","aliases":["2 Kön","2 Könige"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Chronik","aliases":["1 Chr","1 Chronik"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Chronik","aliases":["2 Chr","2 Chronik"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Esra","aliases":["Esra"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Nehemia","aliases":["Neh","Nehemia"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tobit","aliases":["Tob","Tobit"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Judit","aliases":["Jdt","Judit"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Ester","aliases":["Est","Ester"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Makkabäer","aliases":["1 Makk","1 Makkabäer"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Makkabäer","aliases":["2 Makk","2 Makkabäer"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Ijob","aliases":["Ijob"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Psalmen","aliases":["Ps","Psalmen"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Sprichwörter","aliases":["Spr","Sprichwörter"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Kohelet","aliases":["Koh","Kohelet"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Hohelied","aliases":["Hld","Hohelied"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Weisheit","aliases":["Weish","Weisheit"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Jesus Sirach","aliases":["Sir","Jesus Sirach"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Jesaja","aliases":["Jes","Jesaja"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Jeremia","aliases":["Jer","Jeremia"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Klagelieder","aliases":["Klgl","Klagelieder"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Baruch","aliases":["Bar","Baruch"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ezechiel","aliases":["Ez","Ezechiel"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Daniel","aliases":["Dan","Daniel"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Hosea","aliases":["Hos","Hosea"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Joel","aliases":["Joel"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Amos","aliases":["Am","Amos"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Obadja","aliases":["Obd","Obadja"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Jona","aliases":["Jona"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Micha","aliases":["Mi","Micha"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Nahum","aliases":["Nah","Nahum"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Habakuk","aliases":["Hab","Habakuk"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Zefanja","aliases":["Zef","Zefanja"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Haggai","aliases":["Hag","Haggai"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Sacharja","aliases":["Sach","Sacharja"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Maleachi","aliases":["Mal","Maleachi"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Matthäus","aliases":["Mt","Matthäus"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Markus","aliases":["Mk","Markus"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Lukas","aliases":["Lk","Lukas"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"Johannes","aliases":["Joh","Johannes"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Apostelgeschichte","aliases":["Apg","Apostelgeschichte"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Römer","aliases":["Röm","Römer"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Korinther","aliases":["1 Kor","1 Korinther"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Korinther","aliases":["2 Kor","2 Korinther"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Galater","aliases":["Gal","Galater"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Epheser","aliases":["Eph","Epheser"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Philipper","aliases":["Phil","Philipper"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Kolosser","aliases":["Kol","Kolosser"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Thessalonicher","aliases":["1 Thess","1 Thessalonicher"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Thessalonicher","aliases":["2 Thess","2 Thessalonicher"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Timotheus","aliases":["1 Tim","1 Timotheus"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Timotheus","aliases":["2 Tim","2 Timotheus"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Titus","aliases":["Tit","Titus"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Philemon","aliases":["Phlm","Philemon"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hebräer","aliases":["Hebr","Hebräer"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Jakobus","aliases":["Jak","Jakobus"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Petrus","aliases":["1 Petr","1 Petrus"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Petrus","aliases":["2 Petr","2 Petrus"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 Johannes","aliases":["1 Joh","1 Johannes"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 Johannes","aliases":["2 Joh","2 Johannes"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 Johannes","aliases":["3 Joh","3 Johannes"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Judas","aliases":["Jud","Judas"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Offenbarung","aliases":["Offb","Offenbarung"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
