// V27.7: query this table only for VN. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "vn",
  "appLanguage": "VN",
  "label": "베트남어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "Existing app bibleMap; GKPV book names and Vietnamese lectionary introductions",
  "readingIntroSources": [
    "https://vntaiwan.catholic.org.tw/06news/kyhieukt.pdf",
    "https://www.tonggiaophanhanoi.org/le-chung-ve-cac-thanh-muc-tu/",
    "https://www.tonggiaophanhanoi.org/le-chung-ve-cac-thanh-tu-dao/"
  ],
  "readingIntros": {
    "GEN": "Bài trích sách Sáng thế.",
    "EXO": "Bài trích sách Xuất hành.",
    "LEV": "Bài trích sách Lê-vi.",
    "NUM": "Bài trích sách Dân số.",
    "DEU": "Bài trích sách Đệ nhị luật.",
    "JOS": "Bài trích sách Giô-suê.",
    "JDG": "Bài trích sách Thủ lãnh.",
    "RUT": "Bài trích sách Rút.",
    "1SA": "Bài trích sách Sa-mu-en quyển thứ nhất.",
    "2SA": "Bài trích sách Sa-mu-en quyển thứ hai.",
    "1KI": "Bài trích sách các Vua quyển thứ nhất.",
    "2KI": "Bài trích sách các Vua quyển thứ hai.",
    "1CH": "Bài trích sách Sử biên niên quyển thứ nhất.",
    "2CH": "Bài trích sách Sử biên niên quyển thứ hai.",
    "EZR": "Bài trích sách Ét-ra.",
    "NEH": "Bài trích sách Nơ-khe-mi-a.",
    "TOB": "Bài trích sách Tô-bi-a.",
    "JDT": "Bài trích sách Giu-đi-tha.",
    "EST": "Bài trích sách Ét-te.",
    "1MA": "Bài trích sách Ma-ca-bê quyển thứ nhất.",
    "2MA": "Bài trích sách Ma-ca-bê quyển thứ hai.",
    "JOB": "Bài trích sách Gióp.",
    "PSA": "Bài trích sách Thánh vịnh.",
    "PRO": "Bài trích sách Châm ngôn.",
    "ECC": "Bài trích sách Giảng viên.",
    "SNG": "Bài trích sách Diễm ca.",
    "WIS": "Bài trích sách Khôn ngoan.",
    "SIR": "Bài trích sách Huấn ca.",
    "ISA": "Bài trích sách ngôn sứ I-sai-a.",
    "JER": "Bài trích sách ngôn sứ Giê-rê-mi-a.",
    "LAM": "Bài trích sách Ai ca.",
    "BAR": "Bài trích sách ngôn sứ Ba-rúc.",
    "EZK": "Bài trích sách ngôn sứ Ê-dê-ki-en.",
    "DAN": "Bài trích sách ngôn sứ Đa-ni-en.",
    "HOS": "Bài trích sách ngôn sứ Hô-sê.",
    "JOL": "Bài trích sách ngôn sứ Giô-en.",
    "AMO": "Bài trích sách ngôn sứ A-mốt.",
    "OBA": "Bài trích sách ngôn sứ Ô-va-đi-a.",
    "JON": "Bài trích sách ngôn sứ Giô-na.",
    "MIC": "Bài trích sách ngôn sứ Mi-kha.",
    "NAM": "Bài trích sách ngôn sứ Na-khum.",
    "HAB": "Bài trích sách ngôn sứ Kha-ba-cúc.",
    "ZEP": "Bài trích sách ngôn sứ Xô-phô-ni-a.",
    "HAG": "Bài trích sách ngôn sứ Khác-gai.",
    "ZEC": "Bài trích sách ngôn sứ Da-ca-ri-a.",
    "MAL": "Bài trích sách ngôn sứ Ma-la-khi.",
    "MAT": "Tin Mừng Chúa Giê-su Ki-tô theo thánh Mát-thêu.",
    "MRK": "Tin Mừng Chúa Giê-su Ki-tô theo thánh Mác-cô.",
    "LUK": "Tin Mừng Chúa Giê-su Ki-tô theo thánh Lu-ca.",
    "JHN": "Tin Mừng Chúa Giê-su Ki-tô theo thánh Gio-an.",
    "ACT": "Bài trích sách Công vụ Tông Đồ.",
    "ROM": "Bài trích thư của thánh Phao-lô tông đồ gửi tín hữu Rô-ma.",
    "1CO": "Bài trích thư thứ nhất của thánh Phao-lô tông đồ gửi tín hữu Cô-rin-tô.",
    "2CO": "Bài trích thư thứ hai của thánh Phao-lô tông đồ gửi tín hữu Cô-rin-tô.",
    "GAL": "Bài trích thư của thánh Phao-lô tông đồ gửi tín hữu Ga-lát.",
    "EPH": "Bài trích thư của thánh Phao-lô tông đồ gửi tín hữu Ê-phê-xô.",
    "PHP": "Bài trích thư của thánh Phao-lô tông đồ gửi tín hữu Phi-líp-phê.",
    "COL": "Bài trích thư của thánh Phao-lô tông đồ gửi tín hữu Cô-lô-xê.",
    "1TH": "Bài trích thư thứ nhất của thánh Phao-lô tông đồ gửi tín hữu Thê-xa-lô-ni-ca.",
    "2TH": "Bài trích thư thứ hai của thánh Phao-lô tông đồ gửi tín hữu Thê-xa-lô-ni-ca.",
    "1TI": "Bài trích thư thứ nhất của thánh Phao-lô tông đồ gửi ông Ti-mô-thê.",
    "2TI": "Bài trích thư thứ hai của thánh Phao-lô tông đồ gửi ông Ti-mô-thê.",
    "TIT": "Bài trích thư của thánh Phao-lô tông đồ gửi ông Ti-tô.",
    "PHM": "Bài trích thư của thánh Phao-lô tông đồ gửi ông Phi-lê-môn.",
    "HEB": "Bài trích thư gửi tín hữu Híp-ri.",
    "JAS": "Bài trích thư của thánh Gia-cô-bê tông đồ.",
    "1PE": "Bài trích thư thứ nhất của thánh Phê-rô tông đồ.",
    "2PE": "Bài trích thư thứ hai của thánh Phê-rô tông đồ.",
    "1JN": "Bài trích thư thứ nhất của thánh Gio-an tông đồ.",
    "2JN": "Bài trích thư thứ hai của thánh Gio-an tông đồ.",
    "3JN": "Bài trích thư thứ ba của thánh Gio-an tông đồ.",
    "JUD": "Bài trích thư của thánh Giu-đa tông đồ.",
    "REV": "Bài trích sách Khải huyền của thánh Gio-an tông đồ."
  },
  "books": {
    "GEN": {"koreanName":"창세기","name":"St","aliases":["St"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Xh","aliases":["Xh"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Lv","aliases":["Lv"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Ds","aliases":["Ds"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Đnl","aliases":["Đnl"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Gs","aliases":["Gs"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Tl","aliases":["Tl"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"R","aliases":["R"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Sm","aliases":["1 Sm"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Sm","aliases":["2 Sm"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 V","aliases":["1 V"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 V","aliases":["2 V"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Sb","aliases":["1 Sb"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Sb","aliases":["2 Sb"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Er","aliases":["Er"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Nkm","aliases":["Nkm"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tb","aliases":["Tb"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Gđt","aliases":["Gđt"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Et","aliases":["Et"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Mcb","aliases":["1 Mcb"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Mcb","aliases":["2 Mcb"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"G","aliases":["G"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Tv","aliases":["Tv"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Cn","aliases":["Cn"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Gv","aliases":["Gv"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Dc","aliases":["Dc"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Kn","aliases":["Kn"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Hc","aliases":["Hc"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Is","aliases":["Is"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Gr","aliases":["Gr"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Ac","aliases":["Ac"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Br","aliases":["Br"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ed","aliases":["Ed"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Đn","aliases":["Đn"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Hs","aliases":["Hs"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Ge","aliases":["Ge"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Am","aliases":["Am"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Ôv","aliases":["Ôv"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Gn","aliases":["Gn"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Mk","aliases":["Mk"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Nk","aliases":["Nk"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Kb","aliases":["Kb"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"Xp","aliases":["Xp"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Kg","aliases":["Kg"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Dcr","aliases":["Dcr"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Ml","aliases":["Ml"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Mt","aliases":["Mt"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Mc","aliases":["Mc"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Lc","aliases":["Lc"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"Ga","aliases":["Ga"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Cv","aliases":["Cv"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Rm","aliases":["Rm"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Cr","aliases":["1 Cr"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Cr","aliases":["2 Cr"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Gl","aliases":["Gl"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Ep","aliases":["Ep"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Pl","aliases":["Pl"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Cl","aliases":["Cl"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Tx","aliases":["1 Tx"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Tx","aliases":["2 Tx"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Tm","aliases":["1 Tm"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Tm","aliases":["2 Tm"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Tt","aliases":["Tt"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Plm","aliases":["Plm"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hr","aliases":["Hr"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Gc","aliases":["Gc"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Pr","aliases":["1 Pr"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Pr","aliases":["2 Pr"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 Ga","aliases":["1 Ga"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 Ga","aliases":["2 Ga"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 Ga","aliases":["3 Ga"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Gđ","aliases":["Gđ"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Kh","aliases":["Kh"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
