// V27.7: query this table only for ZH. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "zh",
  "appLanguage": "ZH",
  "label": "중국어 번체",
  "status": "language-scoped",
  "coverage": "73 Catholic books; user's 71 entries plus Jonah/Micah from Catholic index; representative aliases, not exhaustive",
  "source": "User Catholic list supplied 2026-09-10, reconciled with CCREADBIBLE traditional Chinese Catholic index and existing Taiwan CRBC daily corpus. Earlier Protestant screenshots and Joshua override withdrawn.",
  "sources": [
    "https://www.ccreadbible.org/Members/Bona/index.html-1",
    "https://sliturgy.catholic.org.tw/禮儀及聖事/禮儀經文/每日彌撒"
  ],
  "notes": [
    "撒mu爾紀上/下 corrected to 撒慕爾紀上/下; 托bit傳 corrected to 多俾亞傳. Mixed-script typos are not lookup aliases.",
    "若, 瑪, 厄, 雅 and Jud are ambiguous in the supplied list; never choose the first book. A source-specific mapping would require separately verified metadata.",
    "Added Jonah/Micah full names only; short aliases not verified here.",
    "Psalm numbering/verse equivalence is not established by this book-name table."
  ],
  "books": {
    "GEN": {"koreanName":"창세기","name":"創世紀","aliases":["創世紀","創世記","創","Gen"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"出谷紀","aliases":["出谷紀","出","Exo"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"肋未紀","aliases":["肋未紀","肋","Lev"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"戶籍紀","aliases":["戶籍紀","戶","Num"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"申命紀","aliases":["申命紀","申","Deu"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"若蘇厄書","aliases":["若蘇厄書","若","Jos"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"民長紀","aliases":["民長紀","民","Jud"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"盧德傳","aliases":["盧德傳","盧","Rut"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"撒慕爾紀上","aliases":["撒慕爾紀上","撒上","1Sa"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"撒慕爾紀下","aliases":["撒慕爾紀下","撒下","2Sa"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"列王紀上","aliases":["列王紀上","列上","1Ki"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"列王紀下","aliases":["列王紀下","列下","2Ki"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"編年紀上","aliases":["編年紀上","歷代志上","歷上","1Ch"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"編年紀下","aliases":["編年紀下","歷代志下","歷下","2Ch"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"厄斯德拉上","aliases":["厄斯德拉上","厄上","Ezr","厄斯德拉卷上"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"厄斯德拉下","aliases":["厄斯德拉下","厄下","Neh","乃赫米雅"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"多俾亞傳","aliases":["多俾亞傳","托","Tob"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"友弟德傳","aliases":["友弟德傳","友","Jdt"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"艾斯德爾傳","aliases":["艾斯德爾傳","艾","Est"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"瑪加伯上","aliases":["瑪加伯上","瑪上","1Ma","瑪加伯書上"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"瑪加伯下","aliases":["瑪加伯下","瑪下","2Ma","瑪加伯書下"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"約伯傳","aliases":["約伯傳","伯","Job"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"聖詠集","aliases":["聖詠集","聖詠","詠","Psa"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"箴言","aliases":["箴言","箴","Pro"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"訓道篇","aliases":["訓道篇","訓","Ecc"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"雅歌","aliases":["雅歌","雅","Son"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"智慧篇","aliases":["智慧篇","智","Wis","智慧書"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"德訓篇","aliases":["德訓篇","德","Sir"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"依撒意亞","aliases":["依撒意亞","依撒意亞書","以賽亞書","依","Isa","依撒意亞先知書"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"耶肋米亞","aliases":["耶肋米亞","耶肋米亞書","耶利米亞書","耶","Jer","耶肋米亞先知書"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"哀歌","aliases":["哀歌","哀","Lam"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"巴路克","aliases":["巴路克","巴路克書","巴","Bar","巴路克先知書"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"厄則克耳","aliases":["厄則克耳","厄則克耳書","厄澤克耳書","厄","Eze","厄則克耳先知書"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"達尼爾","aliases":["達尼爾","達尼爾書","達","Dan","達尼爾先知書"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"歐瑟亞","aliases":["歐瑟亞","歐瑟亞書","歐","Hos","歐瑟亞先知書"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"岳厄爾","aliases":["岳厄爾","岳厄爾書","若厄爾書","若","Joe","岳厄爾先知書"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"亞毛斯","aliases":["亞毛斯","亞毛斯書","阿摩司書","摩","Amo","亞毛斯先知書"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"亞北底亞","aliases":["亞北底亞","亞北底亞書","亞","Oba"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"約納","aliases":["約納","約納書","約納先知書"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"米該亞","aliases":["米該亞","米該亞書","米該亞先知書"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"納鴻","aliases":["納鴻","納鴻書","納胡姆書","納","Nah","納鴻先知書"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"哈巴谷","aliases":["哈巴谷","哈巴谷書","哈","Hab","哈巴谷先知書"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"索福尼亞","aliases":["索福尼亞","索福尼亞書","索","Zep","索福尼亞先知書"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"哈蓋","aliases":["哈蓋","哈蓋書","蓋","Hag","哈蓋先知書"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"匝加利亞","aliases":["匝加利亞","匝加利亞書","匝","Zec","匝加利亞先知書"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"瑪拉基亞","aliases":["瑪拉基亞","瑪拉基亞書","瑪","Mal","瑪拉基亞先知書"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"瑪竇福音","aliases":["瑪竇福音","聖瑪竇福音","瑪","Mat"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"馬爾谷福音","aliases":["馬爾谷福音","聖馬爾谷福音","瑪谷福音","聖瑪谷福音","谷","Mar"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"路加福音","aliases":["路加福音","聖路加福音","路","Luk"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"若望福音","aliases":["若望福音","聖若望福音","若","Joh"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"宗徒大事錄","aliases":["宗徒大事錄","宗","Act"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"羅馬書","aliases":["羅馬書","羅","Rom","聖保祿宗徒致羅馬人書"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"格林多前書","aliases":["格林多前書","格前","1Co","聖保祿宗徒致格林多人前書"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"格林多後書","aliases":["格林多後書","格後","2Co","聖保祿宗徒致格林多人後書"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"迦拉達書","aliases":["迦拉達書","加拉達書","加","Gal","聖保祿宗徒致迦拉達人書"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"厄弗所書","aliases":["厄弗所書","厄","Eph","聖保祿宗徒致厄弗所人書"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"斐理伯書","aliases":["斐理伯書","斐","Phi","聖保祿宗徒致斐理伯人書"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"哥羅森書","aliases":["哥羅森書","哥","Col","聖保祿宗徒致哥羅森人書"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"得撒洛尼前書","aliases":["得撒洛尼前書","帖撒羅尼迦前書","帖前","1Th","聖保祿宗徒致得撒洛尼人前書"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"得撒洛尼後書","aliases":["得撒洛尼後書","帖撒羅尼迦後書","帖後","2Th","聖保祿宗徒致得撒洛尼人後書"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"弟茂德前書","aliases":["弟茂德前書","弟前","1Ti","聖保祿宗徒致茂德前書"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"弟茂德後書","aliases":["弟茂德後書","弟後","2Ti","聖保祿宗徒致茂德後書","聖保祿宗徒致弟茂德後書"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"弟鐸書","aliases":["弟鐸書","鐸","Tit","聖保祿宗徒致弟鐸書","聖保祿宗徒致迪德書"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"費肋孟書","aliases":["費肋孟書","門","Phm"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"希伯來書","aliases":["希伯來書","希","Heb","致希伯來人書"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"雅各伯書","aliases":["雅各伯書","雅","Jas","聖雅格書","聖雅格宗徒書","聖雅各伯書"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"伯多祿前書","aliases":["伯多祿前書","伯前","1Pe","聖伯鐸宗徒前書","聖伯鐸前書","聖伯多祿前書"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"伯多祿後書","aliases":["伯多祿後書","伯後","2Pe","聖伯鐸宗徒後書","聖伯多祿後書"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"若望一書","aliases":["若望一書","若一","1Jo","聖若望宗徒壹書","聖若望壹書","聖若望一書"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"若望二書","aliases":["若望二書","若二","2Jo"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"若望三書","aliases":["若望三書","若三","3Jo"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"猶達書","aliases":["猶達書","猶","Jud"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"若望默示錄","aliases":["若望默示錄","默","Rev","聖若望默示錄","聖若望宗徒默示錄","默示錄"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
