// V27.7: query this table only for LA. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "la",
  "appLanguage": "LA",
  "label": "라틴어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "Existing app bibleMap; Korean full names from notation audit",
  "books": {
    "GEN": {"koreanName":"창세기","name":"Gen.","aliases":["Gen."],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"Ex.","aliases":["Ex."],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"Lv.","aliases":["Lv."],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"Nm.","aliases":["Nm."],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"Dt.","aliases":["Dt."],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"Ios.","aliases":["Ios."],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"Idc.","aliases":["Idc."],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"Rt.","aliases":["Rt."],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"1 Sm.","aliases":["1 Sm."],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"2 Sm.","aliases":["2 Sm."],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"1 Reg.","aliases":["1 Reg."],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"2 Reg.","aliases":["2 Reg."],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"1 Chr.","aliases":["1 Chr."],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"2 Chr.","aliases":["2 Chr."],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"Ezr.","aliases":["Ezr."],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"Neh.","aliases":["Neh."],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"Tb.","aliases":["Tb."],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"Idt.","aliases":["Idt."],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"Est.","aliases":["Est."],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"1 Mc.","aliases":["1 Mc."],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"2 Mc.","aliases":["2 Mc."],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"Iob.","aliases":["Iob."],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"Ps.","aliases":["Ps."],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"Prv.","aliases":["Prv."],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"Eccl.","aliases":["Eccl."],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"Ct.","aliases":["Ct."],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"Sap.","aliases":["Sap."],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"Sir.","aliases":["Sir."],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"Is.","aliases":["Is."],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"Ier.","aliases":["Ier."],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"Lam.","aliases":["Lam."],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"Bar.","aliases":["Bar."],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"Ez.","aliases":["Ez."],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"Dn.","aliases":["Dn."],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"Os.","aliases":["Os."],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"Ioel.","aliases":["Ioel."],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"Am.","aliases":["Am."],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"Abd.","aliases":["Abd."],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"Ion.","aliases":["Ion."],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"Mi.","aliases":["Mi."],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"Na.","aliases":["Na."],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"Hb.","aliases":["Hb."],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"So.","aliases":["So."],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"Ag.","aliases":["Ag."],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"Za.","aliases":["Za."],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"Ml.","aliases":["Ml."],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"Mt.","aliases":["Mt."],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"Mc.","aliases":["Mc."],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"Lc.","aliases":["Lc."],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"Io.","aliases":["Io."],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"Act.","aliases":["Act."],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"Rom.","aliases":["Rom."],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"1 Cor.","aliases":["1 Cor."],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"2 Cor.","aliases":["2 Cor."],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"Gal.","aliases":["Gal."],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"Eph.","aliases":["Eph."],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"Phil.","aliases":["Phil."],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"Col.","aliases":["Col."],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"1 Thess.","aliases":["1 Thess."],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"2 Thess.","aliases":["2 Thess."],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"1 Tim.","aliases":["1 Tim."],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"2 Tim.","aliases":["2 Tim."],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"Tit.","aliases":["Tit."],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"Phlm.","aliases":["Phlm."],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"Hebr.","aliases":["Hebr."],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"Iac.","aliases":["Iac."],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"1 Pt.","aliases":["1 Pt."],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"2 Pt.","aliases":["2 Pt."],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"1 Io.","aliases":["1 Io."],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"2 Io.","aliases":["2 Io."],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"3 Io.","aliases":["3 Io."],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"Iud.","aliases":["Iud."],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"Apc.","aliases":["Apc."],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
