// V27.7: query this table only for JP. Canonical IDs join books, not alias namespaces.
(function (root) {
  const table = {
  "schemaVersion": 1,
  "language": "jp",
  "appLanguage": "JP",
  "label": "일본어",
  "status": "language-scoped",
  "coverage": "73 books; representative aliases only; publisher/source variants not exhaustive",
  "source": "Existing app bibleMap; Korean full names from notation audit",
  "books": {
    "GEN": {"koreanName":"창세기","name":"創","aliases":["創"],"koreanKey":"창세"},
    "EXO": {"koreanName":"탈출기","name":"出","aliases":["出"],"koreanKey":"탈출"},
    "LEV": {"koreanName":"레위기","name":"レビ","aliases":["レビ"],"koreanKey":"레위"},
    "NUM": {"koreanName":"민수기","name":"民","aliases":["民"],"koreanKey":"민수"},
    "DEU": {"koreanName":"신명기","name":"申","aliases":["申"],"koreanKey":"신명"},
    "JOS": {"koreanName":"여호수아기","name":"ヨシュ","aliases":["ヨシュ"],"koreanKey":"여호"},
    "JDG": {"koreanName":"판관기","name":"士","aliases":["士"],"koreanKey":"판관"},
    "RUT": {"koreanName":"룻기","name":"ルツ","aliases":["ルツ"],"koreanKey":"룻"},
    "1SA": {"koreanName":"사무엘기 상권","name":"サム上","aliases":["サム上"],"koreanKey":"1사무"},
    "2SA": {"koreanName":"사무엘기 하권","name":"サム下","aliases":["サム下"],"koreanKey":"2사무"},
    "1KI": {"koreanName":"열왕기 상권","name":"列上","aliases":["列上"],"koreanKey":"1열왕"},
    "2KI": {"koreanName":"열왕기 하권","name":"列下","aliases":["列下"],"koreanKey":"2열왕"},
    "1CH": {"koreanName":"역대기 상권","name":"歴上","aliases":["歴上"],"koreanKey":"1역대"},
    "2CH": {"koreanName":"역대기 하권","name":"歴下","aliases":["歴下"],"koreanKey":"2역대"},
    "EZR": {"koreanName":"에즈라기","name":"エズ","aliases":["エズ"],"koreanKey":"에즈"},
    "NEH": {"koreanName":"느헤미야기","name":"ネヘ","aliases":["ネヘ"],"koreanKey":"느헤"},
    "TOB": {"koreanName":"토빗기","name":"トビ","aliases":["トビ"],"koreanKey":"토빗"},
    "JDT": {"koreanName":"유딧기","name":"ユデ","aliases":["ユデ"],"koreanKey":"유딧"},
    "EST": {"koreanName":"에스테르기","name":"エス","aliases":["エス"],"koreanKey":"에스"},
    "1MA": {"koreanName":"마카베오기 상권","name":"マカ一","aliases":["マカ一"],"koreanKey":"1마카"},
    "2MA": {"koreanName":"마카베오기 하권","name":"マカ二","aliases":["マカ二"],"koreanKey":"2마카"},
    "JOB": {"koreanName":"욥기","name":"ヨブ","aliases":["ヨブ"],"koreanKey":"욥"},
    "PSA": {"koreanName":"시편","name":"詩","aliases":["詩"],"koreanKey":"시편"},
    "PRO": {"koreanName":"잠언","name":"箴","aliases":["箴"],"koreanKey":"잠언"},
    "ECC": {"koreanName":"코헬렛","name":"コヘ","aliases":["コヘ"],"koreanKey":"코헬"},
    "SNG": {"koreanName":"아가","name":"雅","aliases":["雅"],"koreanKey":"아가"},
    "WIS": {"koreanName":"지혜서","name":"知","aliases":["知"],"koreanKey":"지혜"},
    "SIR": {"koreanName":"집회서","name":"シラ","aliases":["シラ"],"koreanKey":"집회"},
    "ISA": {"koreanName":"이사야서","name":"イザ","aliases":["イザ"],"koreanKey":"이사"},
    "JER": {"koreanName":"예레미야서","name":"エレ","aliases":["エレ"],"koreanKey":"예레"},
    "LAM": {"koreanName":"애가","name":"哀","aliases":["哀"],"koreanKey":"애가"},
    "BAR": {"koreanName":"바룩서","name":"バル","aliases":["バル"],"koreanKey":"바룩"},
    "EZK": {"koreanName":"에제키엘서","name":"エゼ","aliases":["エゼ"],"koreanKey":"에제"},
    "DAN": {"koreanName":"다니엘서","name":"ダニ","aliases":["ダニ"],"koreanKey":"다니"},
    "HOS": {"koreanName":"호세아서","name":"ホセ","aliases":["ホセ"],"koreanKey":"호세"},
    "JOL": {"koreanName":"요엘서","name":"ヨエ","aliases":["ヨエ"],"koreanKey":"요엘"},
    "AMO": {"koreanName":"아모스서","name":"アモ","aliases":["アモ"],"koreanKey":"아모"},
    "OBA": {"koreanName":"오바드야서","name":"オバ","aliases":["オバ"],"koreanKey":"오바"},
    "JON": {"koreanName":"요나서","name":"ヨナ","aliases":["ヨナ"],"koreanKey":"요나"},
    "MIC": {"koreanName":"미카서","name":"ミカ","aliases":["ミカ"],"koreanKey":"미카"},
    "NAM": {"koreanName":"나훔서","name":"ナホ","aliases":["ナホ"],"koreanKey":"나훔"},
    "HAB": {"koreanName":"하바쿡서","name":"ハバ","aliases":["ハバ"],"koreanKey":"하바"},
    "ZEP": {"koreanName":"스바니야서","name":"ゼファ","aliases":["ゼファ"],"koreanKey":"스파"},
    "HAG": {"koreanName":"하까이서","name":"ハガ","aliases":["ハガ"],"koreanKey":"학개"},
    "ZEC": {"koreanName":"즈카르야서","name":"ゼカ","aliases":["ゼカ"],"koreanKey":"즈카"},
    "MAL": {"koreanName":"말라키서","name":"マラ","aliases":["マラ"],"koreanKey":"말라"},
    "MAT": {"koreanName":"마태오 복음","name":"マタ","aliases":["マタ"],"koreanKey":"마태"},
    "MRK": {"koreanName":"마르코 복음","name":"マル","aliases":["マル"],"koreanKey":"마르"},
    "LUK": {"koreanName":"루카 복음","name":"ルカ","aliases":["ルカ"],"koreanKey":"루카"},
    "JHN": {"koreanName":"요한 복음","name":"ヨハ","aliases":["ヨハ"],"koreanKey":"요한"},
    "ACT": {"koreanName":"사도행전","name":"使","aliases":["使"],"koreanKey":"사도"},
    "ROM": {"koreanName":"로마서","name":"ロマ","aliases":["ロマ"],"koreanKey":"로마"},
    "1CO": {"koreanName":"코린토 1서","name":"コリ一","aliases":["コリ一"],"koreanKey":"1코린"},
    "2CO": {"koreanName":"코린토 2서","name":"コリ二","aliases":["コリ二"],"koreanKey":"2코린"},
    "GAL": {"koreanName":"갈라티아서","name":"ガラ","aliases":["ガラ"],"koreanKey":"갈라"},
    "EPH": {"koreanName":"에페소서","name":"エフェ","aliases":["エフェ"],"koreanKey":"에페"},
    "PHP": {"koreanName":"필리피서","name":"フィリ","aliases":["フィリ"],"koreanKey":"필리"},
    "COL": {"koreanName":"콜로새서","name":"コロ","aliases":["コロ"],"koreanKey":"콜로"},
    "1TH": {"koreanName":"테살로니카 1서","name":"テサ一","aliases":["テサ一"],"koreanKey":"1테살"},
    "2TH": {"koreanName":"테살로니카 2서","name":"テサ二","aliases":["テサ二"],"koreanKey":"2테살"},
    "1TI": {"koreanName":"티모테오 1서","name":"テモ一","aliases":["テモ一"],"koreanKey":"1티모"},
    "2TI": {"koreanName":"티모테오 2서","name":"テモ二","aliases":["テモ二"],"koreanKey":"2티모"},
    "TIT": {"koreanName":"티토서","name":"テト","aliases":["テト"],"koreanKey":"티토"},
    "PHM": {"koreanName":"필레몬서","name":"フィレ","aliases":["フィレ"],"koreanKey":"필레"},
    "HEB": {"koreanName":"히브리서","name":"ヘブ","aliases":["ヘブ"],"koreanKey":"히브"},
    "JAS": {"koreanName":"야고보서","name":"ヤコ","aliases":["ヤコ"],"koreanKey":"야고"},
    "1PE": {"koreanName":"베드로 1서","name":"ペト一","aliases":["ペト一"],"koreanKey":"1베드"},
    "2PE": {"koreanName":"베드로 2서","name":"ペト二","aliases":["ペト二"],"koreanKey":"2베드"},
    "1JN": {"koreanName":"요한 1서","name":"ヨハ一","aliases":["ヨハ一"],"koreanKey":"1요한"},
    "2JN": {"koreanName":"요한 2서","name":"ヨハ二","aliases":["ヨハ二"],"koreanKey":"2요한"},
    "3JN": {"koreanName":"요한 3서","name":"ヨハ三","aliases":["ヨハ三"],"koreanKey":"3요한"},
    "JUD": {"koreanName":"유다서","name":"ユダ","aliases":["ユダ"],"koreanKey":"유다"},
    "REV": {"koreanName":"요한 묵시록","name":"黙","aliases":["黙"],"koreanKey":"묵시"}
  }
};
  (root.bibleLanguageTables ||= {})[table.appLanguage] = table;
  if (typeof module !== 'undefined' && module.exports) module.exports = table;
})(globalThis);
