#!/usr/bin/env python3
"""Compile per-country Python definitions into the static browser registry."""

import argparse
import datetime as dt
import json
import re
import runpy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFINITIONS = Path(__file__).with_name("special_liturgies")
OUTPUT = ROOT / "JS file" / "country_special_liturgies.js"
sys.path.insert(0, str(DEFINITIONS))
from common import UNIVERSAL  # noqa: E402

LANGUAGES = {"KR", "VN", "EN", "JP", "LA", "ZH", "IT", "PT", "ES", "DE"}
SECTIONS = {"entrance", "collect", "reading1", "psalm", "reading2", "Sequence", "gospel_accl", "gospel", "prayer_offerings", "preface", "communion", "prayer_after"}


def validate_mass(entry):
    assert isinstance(entry.get("names", {}), dict), "names must be a language map"
    for lang, data in entry.get("data", {}).items():
        assert lang in LANGUAGES, f"Unsupported language: {lang}"
        assert isinstance(data, dict), "data must contain parsed section maps"
        assert set(data) <= SECTIONS, f"Unknown sections: {set(data) - SECTIONS}"
    for url in entry.get("sourceUrls", {}).values():
        assert re.match(r"^https?://", url), "sourceUrls must be HTTP(S) URLs"


def validate_profile(profile):
    seen = set()
    for entry in profile.get("vigils", []):
        key = entry["id"]
        assert re.fullmatch(r"[a-z][a-z0-9_]*", key) and key not in seen, f"Invalid/duplicate vigil ID: {key}"
        seen.add(key)
        validate_mass(entry)
        rules = [rule for rule in ("dates", "monthDay", "easterOffset") if rule in entry]
        assert len(rules) == 1, f"{key}: specify exactly one date rule"
        for date in entry.get("dates", []):
            assert dt.date.fromisoformat(date).isoformat() == date
        if "monthDay" in entry:
            assert dt.date.fromisoformat(f"2000-{entry['monthDay']}").strftime("%m-%d") == entry["monthDay"]
        if "easterOffset" in entry:
            assert isinstance(entry["easterOffset"], int)
        assert 0 <= entry.get("hour", 19) <= 23
        assert entry.get("color", "gold") in {"gold", "white", "red", "purple", "green", "black", "rose"}
    for choice, entry in profile.get("allSouls", {}).items():
        assert choice in {"first", "second", "third"}
        validate_mass(entry)


def build():
    validate_profile(UNIVERSAL)
    countries = {}
    for file in sorted(DEFINITIONS.glob("*.py")):
        if file.name == "common.py":
            continue
        profile = runpy.run_path(str(file))["SPECIAL_LITURGIES"]
        validate_profile(profile)
        keys = profile["jurisdiction"]
        for key in keys if isinstance(keys, list) else [keys]:
            assert key not in countries, f"Duplicate country: {key}"
            countries[key] = profile
    payload = {"schemaVersion": 1, "universal": UNIVERSAL, "countries": countries}
    return "// Generated by tools/build-special-liturgies.py; edit tools/special_liturgies/*.py.\n" + "globalThis.countrySpecialLiturgies = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the committed browser registry is current")
    args = parser.parse_args()
    source = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != source:
            raise SystemExit("Special liturgy registry is stale; run python tools/build-special-liturgies.py")
        print("Special liturgy registry is valid and current.")
    else:
        OUTPUT.write_text(source, encoding="utf-8", newline="\n")
        print(f"Built {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
