#!/usr/bin/env python3
"""Index dated Saint propers and explicit preface rubrics in the supplied Missal."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PDF = ROOT / '참고자료/미사/전문/영어.pdf'
OUTPUT = ROOT / 'JS file/missal_preface_index.js'
MONTHS = {name: index + 1 for index, name in enumerate('January February March April May June July August September October November December'.split())}


def build(pdf_path=PDF):
    import pypdfium2 as pdfium
    document = pdfium.PdfDocument(pdf_path)
    chunks = []
    try:
        for number in range(799, 1026):
            page = document[number - 1]
            text = page.get_textpage()
            chunks.append(f'\n[[PAGE {number}]]\n' + text.get_text_range().replace('\r', ''))
            text.close()
            page.close()
    finally:
        document.close()
    source = '\n'.join(chunks)
    dates = list(re.finditer(r'(?m)^(' + '|'.join(MONTHS) + r')\s+(\d{1,2})\s*$', source))
    entries = []
    for index, date in enumerate(dates):
        block = source[date.end():dates[index + 1].start() if index + 1 < len(dates) else len(source)]
        header = re.split(r'Entrance\s+Antiphon|Collect|From the Common', block)[0]
        header = re.sub(r'\[\[PAGE \d+\]\]|\b(?:Memorial|Feast|Solemnity)\b|\d+', '', header).strip()
        title = re.sub(r'\s+', ' ', header)
        page_matches = list(re.finditer(r'\[\[PAGE (\d+)\]\]', source[:date.start()]))
        page = int(page_matches[-1][1])
        rubrics = re.findall(r'(?m)^Preface[^\n]*', block)
        rubric = re.sub(r'\s+', ' ', ' '.join(rubrics))
        keys = []
        if 'Blessed Virgin Mary' in rubric:
            keys = ['mary_2'] if re.search(r'^Preface II\b', rubric) else ['mary_1', 'mary_2'] if re.search(r'\bor\s+II\b|I\s+or\s+II', rubric) else ['mary_1']
        elif 'Apostles' in rubric:
            keys = ['apostles_2'] if re.search(r'^Preface II\b', rubric) else ['apostles_1', 'apostles_2'] if 'pp.' in rubric else ['apostles_1']
        elif 'Holy Martyrs' in rubric:
            keys = ['martyrs']
        elif 'mission of Saint Joseph' in rubric:
            keys = ['saint_joseph']
        elif 'mission of the Precursor' in rubric:
            keys = ['john_the_baptist']
        elif 'Angels' in rubric:
            keys = ['angels']
        elif 'Nativity of the Lord' in rubric:
            keys = ['nativity_1', 'nativity_2', 'nativity_3']
        elif 'Passion of the Lord' in rubric:
            keys = ['passion_1']
        if not title:
            continue
        entries.append({'date': f'{MONTHS[date[1]]:02d}-{int(date[2]):02d}', 'title': title, 'page': page,
                        'memorial': bool(re.search(r'\bMemorial\b', block[:500])), 'keys': keys,
                        'rubric': rubric, 'common': re.sub(r'\s+', ' ', re.search(r'From the Common[\s\S]*?\)\.', block).group(0)) if re.search(r'From the Common[\s\S]*?\)\.', block) else ''})
    assert len(entries) > 150, 'Incomplete Missal calendar index'
    assert any(entry['date'] == '10-07' and entry['keys'] == ['mary_1', 'mary_2'] for entry in entries)
    prefaces = json.loads(Path(__file__).with_name('missal-preface-corrections.json').read_text(encoding='utf-8'))
    return {'source': 'Supplied Roman Missal, English.pdf, PDF pages 799–1025', 'entries': entries, 'prefaces': prefaces}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--pdf', type=Path, default=PDF, help='Path to the supplied full English Roman Missal')
    args = parser.parse_args()
    payload = build(args.pdf)
    source = '// Generated by tools/build-missal-preface-index.py from the supplied Roman Missal.\n' + 'globalThis.missalPrefaceIndex = ' + json.dumps(payload, ensure_ascii=False, indent=2) + ';\n'
    if args.check:
        assert OUTPUT.read_text(encoding='utf-8') == source, 'Missal preface index is stale'
    else:
        OUTPUT.write_text(source, encoding='utf-8', newline='\n')
    print(f"Indexed {len(payload['entries'])} dated propers; {sum(bool(entry['keys']) for entry in payload['entries'])} explicit preface mappings.")


if __name__ == '__main__':
    main()
