#!/usr/bin/env python3
"""Generate current US Latin-diocese bishop baptismal names from USCCB."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from pathlib import Path

import requests


SOURCE_URL = "https://www.usccb.org/about/bishops-and-dioceses/all-dioceses"
TEXT_SOURCE_URL = f"https://r.jina.ai/http://{SOURCE_URL}"
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "JS file" / "us_bishop_data.js"


def clean(value: str) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


def baptismal_name(person: str) -> str:
    value = re.sub(r"^(?:His Eminence\s+)?(?:Cardinal|Archbishop|Bishop)\s+", "", clean(person))
    tokens = value.split()
    if not tokens:
        return ""
    if re.fullmatch(r"[A-Z]\.", tokens[0]) and len(tokens) > 1:
        return tokens[1].strip(",")
    return tokens[0].strip(",")


def parse_usccb(text: str) -> dict[str, dict]:
    lines = [clean(line) for line in text.splitlines() if clean(line)]
    heading_indexes = [
        index for index, line in enumerate(lines)
        if re.search(r"\b(?:Archdiocese|Diocese|Eparchy|Archeparchy|Ordinariate)\b", line)
        and not re.match(r"^(?:Cardinal|Archbishop|Bishop|Auxiliary|Apostolic|Diocesan)\b", line)
        and not re.search(r"https?://|www\.", line, flags=re.IGNORECASE)
    ]
    entries: dict[str, dict] = {}
    for position, start in enumerate(heading_indexes):
        heading = lines[start]
        if not re.fullmatch(r"(?:Archdiocese|Diocese) of .+", heading):
            continue
        end = heading_indexes[position + 1] if position + 1 < len(heading_indexes) else len(lines)
        section = lines[start + 1:end]
        ordinary = ""
        auxiliaries: list[str] = []
        for index, role in enumerate(section):
            if index == 0:
                continue
            person = section[index - 1]
            is_bishop_person = re.match(r"^(?:Cardinal|Archbishop|Bishop)\s+", person)
            if not is_bishop_person or "Emeritus" in role:
                continue
            if re.match(r"^(?:Archbishop|Bishop) of ", role):
                ordinary = baptismal_name(person)
            elif role.startswith("Apostolic Administrator of ") and not ordinary:
                ordinary = baptismal_name(person)
            elif role.startswith("Auxiliary Bishop of "):
                name = baptismal_name(person)
                if name and name not in auxiliaries:
                    auxiliaries.append(name)
        if ordinary:
            entries[heading] = {
                "ordinary": ordinary,
                "auxiliaries": auxiliaries,
                "collaboratorSummary": len(auxiliaries) >= 2,
            }
    if len(entries) < 160:
        raise RuntimeError(f"USCCB Latin-diocese parse is incomplete: {len(entries)}")
    return entries


def write_javascript(entries: dict[str, dict], output: Path) -> None:
    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    updated_at = dt.date.today().isoformat()
    javascript = f"""// Generated by tools/build-us-bishop-data.py. Do not hand-edit.
(function () {{
  'use strict';
  const sourceUrl = {json.dumps(SOURCE_URL)};
  const rawEntries = {payload};
  const person = name => ({{ en: name, kr: name, vn: name, jp: name, la: name }});
  const target = globalThis.diocesanBishopData && globalThis.diocesanBishopData.entries;
  if (!target) return;
  Object.entries(rawEntries).forEach(([diocese, entry]) => {{
    target[diocese] = {{
      ordinary: person(entry.ordinary),
      auxiliaries: (entry.auxiliaries || []).map(person),
      collaboratorSummary: !!entry.collaboratorSummary,
      sourceUrls: [sourceUrl]
    }};
  }});
  globalThis.usDiocesanBishopDataMeta = {{
    updatedAt: {json.dumps(updated_at)},
    sourceUrl,
    recordCount: Object.keys(rawEntries).length
  }};
}})();
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(javascript, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()
    response = requests.get(TEXT_SOURCE_URL, timeout=90)
    response.raise_for_status()
    entries = parse_usccb(response.text)
    output = Path(args.output).resolve()
    write_javascript(entries, output)
    print(json.dumps({"output": str(output), "records": len(entries), "source": SOURCE_URL}, ensure_ascii=False))


if __name__ == "__main__":
    main()
