from __future__ import annotations

import json
import re
import unicodedata
from collections import OrderedDict
from pathlib import Path

import pypdfium2 as pdfium
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
HYMN_DATA = ROOT / "JS file" / "hymn_data.js"
ASSETS = ROOT / "assets" / "hymns" / "kr-yahweh-jireh"
REF_DIR = ROOT / "\ucc38\uace0\uc790\ub8cc" / "\uc131\uac00"
YAHWEH_MARKER = "\uc57c\ud6fc\uc774\ub808"
BOOK = "\uc57c\ud6fc\uc774\ub808 (\uc2e0\ud310)"

SCALE = 1.16
QUALITY = 20
LEFT_TITLE_MAX_X = 95
TOP_TITLE_Y_MIN = 700
TOP_MARGIN = 20
BOTTOM_MARGIN = 12
FULL_TOP_MARGIN = 36
FULL_BOTTOM_MARGIN = 30


def find_yahweh_pdf() -> Path:
    candidates = sorted(REF_DIR.glob("*.pdf")) if REF_DIR.exists() else []
    candidates.extend(sorted(ROOT.rglob("*.pdf")))
    for path in candidates:
        if YAHWEH_MARKER in path.name:
            return path
    raise FileNotFoundError("Yahweh Jireh PDF was not found")


def find_json_array_after(text: str, marker: str) -> list[dict]:
    start = text.index(marker)
    array_start = text.index("[", start)
    depth = 0
    in_string = False
    escape = False
    for index in range(array_start, len(text)):
        char = text[index]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
            if depth == 0:
                return json.loads(text[array_start:index + 1])
    raise ValueError("hymn data array not found")


def load_hymn_data() -> list[dict]:
    return find_json_array_after(HYMN_DATA.read_text(encoding="utf-8"), "const hymnData")


def write_hymn_data(entries: list[dict]) -> None:
    body = json.dumps(entries, ensure_ascii=False, indent=2)
    HYMN_DATA.write_text(
        "// Hymn index and compressed per-song score images for V22.2.\n"
        "// Generated by tools/generate_hymn_assets.py; YJ multi-song crops repaired by tools/fix_yahweh_hymn_crops.py.\n"
        "(function attachHymnData(global) {\n"
        f"  const hymnData = {body};\n"
        "  global.hymnData = Array.isArray(global.hymnData) && global.hymnData.length\n"
        "    ? global.hymnData\n"
        "    : hymnData;\n"
        "  global.ordoHymnData = hymnData;\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n",
        encoding="utf-8",
    )


def slug_number(value: int) -> str:
    return f"{value:03d}" if value < 1000 else str(value)


def normalize_search(value: str) -> str:
    value = unicodedata.normalize("NFKD", value or "")
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    value = re.sub(r"[^a-z0-9\uac00-\ud7a3]+", " ", value.lower())
    return re.sub(r"\s+", " ", value).strip()


def title_without_annotations(title: str) -> str:
    title = re.sub(r"\[[^\]]+\]", "", title or "")
    title = re.sub(r"\s+", " ", title).strip()
    match = re.match(r"^(.+?)\s+-\s+([A-Za-z][A-Za-z0-9 ',.!?&:-]+)$", title)
    if match:
        return f"{match.group(1).strip()} ({match.group(2).strip()})"
    return title


ALLOWED_TAGS = {
    "\ub300\ub9bc",
    "\ub5bc\uc81c",
    "\uc0ac\uc21c",
    "\ubd80\ud65c",
    "\ubd80\ud65c/\uc2b9\ucc9c",
    "\uc131\ub839",
    "\uc131\uc2ec",
    "\uc131\ud0c4",
}


def section_for_page(page: int) -> str:
    if page < 116:
        return "\ubbf8\uc0ac\uace1"
    if page < 147:
        return "\ub5bc\uc81c"
    if page < 199:
        return ""
    if page < 635:
        return "\uc0dd\ud65c\uc131\uac00"
    return "\ubd80\ub85d"


def normalize_annotation_tag(value: str) -> str:
    key = re.sub(r"\s+", " ", value or "").strip().split(":")[0].strip()
    if key.lower() == "taize":
        return "\ub5bc\uc81c"
    return key if key in ALLOWED_TAGS else ""


def extra_tags(title: str) -> list[str]:
    tags = []
    for value in re.findall(r"\[([^\]]+)\]", title or ""):
        tag = normalize_annotation_tag(value)
        if tag and tag not in tags:
            tags.append(tag)
    return tags


def catholic_links(title: str) -> list[int]:
    links = []
    for value in re.findall(r"\[([^\]]+)\]", title or ""):
        for match in re.finditer(r"\uac00\ud1a8\ub9ad\uc131\uac00\s*(\d{1,3})", value):
            number = int(match.group(1))
            if 1 <= number <= 528 and number not in links:
                links.append(number)
    return links


def yahweh_aliases(number: int, catholic_numbers: list[int]) -> list[str]:
    aliases = [
        f"{BOOK} {number}",
        f"{BOOK} {slug_number(number)}",
        f"{BOOK} {number}\ubc88",
        f"{BOOK} {slug_number(number)}\ubc88",
        f"YJ {number}",
        f"YJ {slug_number(number)}",
        f"YJ{slug_number(number)}",
    ]
    for catholic_number in catholic_numbers:
        aliases.extend([
            f"\uac00\ud1a8\ub9ad\uc131\uac00 {catholic_number}",
            f"\uac00\ud1a8\ub9ad\uc131\uac00 {catholic_number:03d}",
            f"\uac00\ud1a8\ub9ad\uc131\uac00 {catholic_number}\ubc88",
            f"\uac00\ud1a8\ub9ad\uc131\uac00 {catholic_number:03d}\ubc88",
        ])
    return list(dict.fromkeys(aliases))


def line_title_starts(pdf_path: Path) -> list[dict]:
    pdf = pdfium.PdfDocument(str(pdf_path))
    starts = []
    for page_number in range(1, len(pdf) + 1):
        page = pdf[page_number - 1]
        text_page = page.get_textpage()
        text = text_page.get_text_range(0, text_page.count_chars())
        char_index = 0
        for raw_line in text.splitlines(True):
            line = raw_line.strip()
            start_index = char_index
            char_index += len(raw_line)
            match = re.match(r"^(\d{1,3})\.\s+(.+?)\s*$", line)
            if not match:
                continue
            boxes = []
            for i in range(start_index, min(start_index + len(raw_line), text_page.count_chars())):
                ch = text_page.get_text_range(i, 1)
                if ch in "\r\n\t ":
                    continue
                try:
                    boxes.append(text_page.get_charbox(i))
                except Exception:
                    pass
            if not boxes:
                continue
            x0 = min(box[0] for box in boxes)
            if x0 > LEFT_TITLE_MAX_X:
                continue
            y0 = min(box[1] for box in boxes)
            y1 = max(box[3] for box in boxes)
            title = re.sub(r"\s+", " ", match.group(2)).strip()
            starts.append({
                "number": int(match.group(1)),
                "page": page_number,
                "x0": x0,
                "y0": y0,
                "y1": y1,
                "title": title,
            })
    ordered = sorted(starts, key=lambda item: (item["page"], -item["y1"], item["number"]))
    unique = OrderedDict()
    for item in ordered:
        unique.setdefault(item["number"], item)
    return sorted(unique.values(), key=lambda item: (item["page"], -item["y1"], item["number"]))


def image_y(page_height: float, pdf_y: float) -> int:
    return int(round((page_height - pdf_y) * SCALE))


def crop_pdf_page(pdf: pdfium.PdfDocument, page_number: int, top_y: float | None, bottom_y: float | None) -> Image.Image:
    page = pdf[page_number - 1]
    width, height = page.get_size()
    image = page.render(scale=SCALE).to_pil().convert("RGB")
    top = FULL_TOP_MARGIN if top_y is None else max(0, image_y(height, top_y) - TOP_MARGIN)
    bottom = image.height - FULL_BOTTOM_MARGIN if bottom_y is None else min(image.height, image_y(height, bottom_y) - BOTTOM_MARGIN)
    if bottom <= top + 80:
        top = max(0, top - TOP_MARGIN)
        bottom = min(image.height, top + 120)
    return image.crop((0, top, image.width, bottom))


def save_webp(image: Image.Image, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(out_path, "WEBP", quality=QUALITY, method=6)


def build_score_images(pdf_path: Path, starts: list[dict]) -> dict[int, list[dict]]:
    pdf = pdfium.PdfDocument(str(pdf_path))
    score_images_by_number: dict[int, list[dict]] = {}
    for index, start in enumerate(starts):
        next_start = starts[index + 1] if index + 1 < len(starts) else None
        page = pdf[start["page"] - 1]
        _width, page_height = page.get_size()
        if not next_start:
            end_page = len(pdf)
            include_next_cut = False
        elif next_start["page"] == start["page"]:
            end_page = start["page"]
            include_next_cut = True
        elif next_start["y1"] < TOP_TITLE_Y_MIN:
            end_page = next_start["page"]
            include_next_cut = True
        else:
            end_page = next_start["page"] - 1
            include_next_cut = False
        end_page = max(start["page"], min(end_page, len(pdf)))
        count = end_page - start["page"] + 1
        images = []
        for image_index, page_number in enumerate(range(start["page"], end_page + 1), start=1):
            top_y = start["y1"] if page_number == start["page"] else None
            bottom_y = None
            if include_next_cut and next_start and page_number == next_start["page"]:
                bottom_y = next_start["y1"]
            cropped = crop_pdf_page(pdf, page_number, top_y, bottom_y)
            out = ASSETS / f"{slug_number(start['number'])}-{image_index:02d}.webp"
            save_webp(cropped, out)
            images.append({
                "src": out.relative_to(ROOT).as_posix(),
                "label": f"{image_index}/{count}",
            })
        score_images_by_number[start["number"]] = images
    return score_images_by_number


def build_yahweh_entries(pdf_path: Path, starts: list[dict], score_images: dict[int, list[dict]]) -> list[dict]:
    entries = []
    for start in starts:
        number = start["number"]
        raw_title = start["title"]
        title = title_without_annotations(raw_title)
        tags = [BOOK, section_for_page(start["page"]), *extra_tags(raw_title)]
        tags = [tag for tag in dict.fromkeys(tags) if tag]
        entries.append({
            "id": f"kr-yj-{slug_number(number)}",
            "country": "KR",
            "language": "KR",
            "number": slug_number(number),
            "title": title,
            "displayTitle": f"{slug_number(number)}. {title}",
            "book": BOOK,
            "tags": tags,
            "category": " / ".join(tags),
            "lyrics": "",
            "translations": {},
            "firstLine": "",
            "composer": "",
            "lyricist": "",
            "searchAliases": yahweh_aliases(number, catholic_links(raw_title)),
            "scoreImages": score_images.get(number, []),
            "scoreNote": "",
            "copyright": "",
        })
    return entries


def main() -> None:
    pdf_path = find_yahweh_pdf()
    entries = load_hymn_data()
    starts = line_title_starts(pdf_path)
    score_images = build_score_images(pdf_path, starts)
    yahweh_entries = build_yahweh_entries(pdf_path, starts, score_images)
    output = []
    inserted = False
    for entry in entries:
        if str(entry.get("id", "")).startswith("kr-yj-"):
            if not inserted:
                output.extend(yahweh_entries)
                inserted = True
            continue
        output.append(entry)
    if not inserted:
        output.extend(yahweh_entries)
    write_hymn_data(output)
    print(json.dumps({
        "pdf": str(pdf_path),
        "yahweh_entries": len(yahweh_entries),
        "total_entries": len(output),
        "first_missing_repaired": [number for number in [5, 7, 62, 63, 65, 66] if any(e["number"] == slug_number(number) for e in yahweh_entries)],
        "cropped_images": sum(len(images) for images in score_images.values()),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
